const products = [
    160,
    155,
    141,
    167,
    122,
    143,
    113,
    123,
    120,
    120,
    120,
    120,
    160,
    155,
    141,
    167,
    122,
    143,
    113,
    123,
    130,
    140,
    120,
    170,
]

export const productViews = {
    categories: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
    ],
    products: products,
    views: [
        140,
        123,
        120,
        118,
        113,
        127,
        144,
        155,
        141,
        167,
        122,
        143,
        140,
        123,
        120,
        118,
        113,
        127,
        144,
        155,
        141,
        167,
        122,
        143,
    ],
}

export const productsBar = {
    labels: ["Pending", "Resolved", "Cancelled"],
    products: [18, 73, 9,]
}

export const tableSampleData = [
    {
      property: 'type',
      description: 'set the card type, it should be default | gallery | video',
      type: 'String',
      default: '-',
      version: '1.0',
    },
    {
      property: 'image',
      description:
        'set the card image, see: <a target="_blank" href="https://nextjs.org/docs/api-reference/next/image">next/images</a> package for use',
      type: 'object',
      default: '-',
      version: '',
    },
    {
      property: 'numberOfView',
      description: 'it will show if type is video',
      type: 'String',
      default: '-',
      version: '',
    },
    {
      property: 'numberOflike',
      description: 'it will only show for gallery and post type',
      type: 'String',
      default: '-',
      version: '',
    },
    {
      property: 'numberOfcomment',
      description: 'show number of comments on the post',
      type: 'String',
      default: '',
      version: '',
    },
    {
      property: 'onClick',
      description: 'if you want to handle any event',
      type: '(event) => void',
      default: '-',
      version: '',
    },
    {
      property: 'style',
      description: 'add your custom style',
      type: 'React.CSSProperties',
      default: '-',
      version: '',
    },
  ];